<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.12.0.5764" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260302" />
  </ItemGroup>

  <ItemGroup>
    <None Update="boton_objetivo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pantallazo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
